Organization Role
theforeman/foreman-ansible-modules pull request #1112
Opened 2020-12-21 20:30 UTC by hindman-redhat

Draft pull request

2020-12-21 22:55 UTC, willtome commented
@hindman-redhat, currently the variables data structure would look like this
```
foreman_organizations: 
  - name: raleigh
    label: rdu
    server_url: url
    username: user
    password: pass
    validate_certs: no
    state: present
  - name: lanai 
    description: pacific datacenter 
    server_url: url
    username: user
    password: pass
    validate_certs: no
    state: present
  - name: default
    label: boring
    server_url: url
    username: user
    password: pass
    validate_certs: no
    state: present
```

Update so that the authentication vars, `server_url`, `username`, `password`, etc, so they are given once per role invocation with a list of the unique variables `name`, `description`, `label`, etc given as `foreman_organization`. See example below:
```
foreman_server_url: url
foreman_username: user
foreman_password: pass
foreman_validate_certs: no
foreman_organizations: 
  - name: raleigh
    label: rdu
    state: present
  - name: lanai 
    description: pacific datacenter 
  - name: default
    label: boring
    state: absent
```

the first set of authentication vars will go under the "Variables" section of your README and the `foreman_organizations` structure gets documented under the "Organization Data Structure" section of your README.

- [ ] update loop vars
- [ ] update README
- [ ] update examples

2020-12-21 22:56 UTC, willtome commented
Closes #1109

2021-01-05 14:55 UTC, willtome requested changes

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
>  # foreman.organizations
update to fully qualified collection name `theforeman.foreman.organizations`

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
> +|`foreman_server_url`|"present"|no|URL of the Foreman server
`present` is not a valid default for `foreman_server_url`

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
> +|`foreman_username`|""|yes|Username accessing the Foreman Server.||
username and password should not be required. check code for `default(omit)` to verify

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
> +|`validate_certs` |""|no|Whether or not to verify the TLS certificates of the Foreman server.
use `foreman_` prefix for validate_certs variable name. document default value

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
> +|`foreman_description` |""|no|Description of named organization
`foreman_description` doesn't make sense here. perhaps you meant `foreman_organizations` as shown in your example?

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
> +|`foreman_description` |""|no|Description of Named Organization|
no `foreman_` prefix required

2021-01-05 14:55 UTC, willtome commented on roles/organizations/README.md
> +|`label`|`False`|no|Custom Label|
False is not valid default for label

2021-01-07 16:19 UTC, willtome requested changes

2021-01-07 16:19 UTC, willtome commented on roles/organizations/README.md
> +|`foreman_organizations`|"present"|no|Manage the Foreman Organization.|
Default would be `[]`

2021-01-07 16:19 UTC, willtome commented on roles/organizations/README.md
> +|`foreman_validate_certs` |"foreman_"|no|Whether or not to verify the TLS certificates of the Foreman server.|
Default would be `""`

2021-01-11 20:44 UTC, willtome approved these changes

2021-01-12 13:49 UTC, ehelms commented
This diverges from our current variable naming conventions and therefore I believe it should be blocked on either updating to our current standard or waiting until we resolve the proposed naming changes so that we have consistency across our roles.

2021-01-18 18:58 UTC, willtome commented
Opened #1131 to meet the current naming scheme. Leaving the PR as is until #1118 is resolved and this can be merged or closed.

2021-02-02 15:45 UTC, evgeni commented
Given we ended up with having a prefix, this is the way to go :)

2021-04-20 12:07 UTC, evgeni commented
taken over in #1204

2021-04-20 12:07 UTC, closed without merging