Module additions
theforeman/foreman-ansible-modules pull request #1570
Opened 2023-03-13 15:13 UTC by kent-hydra

Adds the following modules:
- architecture_info
- location_info
- operatingsystem_info
- role_info
- user_info
- usergroup_info

Adds `parent` parameter to organization module

Adds `disabled` and `mail_enabled` parameter to user module

2023-03-16 22:33 UTC, kent-hydra commented
Could i get any guidance on the error messages here? Im not really sure whats going on with it. My best guess is the tests do not like the additional parameters being added, but Im not real sure why. I have been using these new/changed modules without any issues.

2023-03-17 10:16 UTC, evgeni requested changes
> Could i get any guidance on the error messages here? Im not really sure whats going on with it. My best guess is the tests do not like the additional parameters being added, but Im not real sure why. I have been using these new/changed modules without any issues.

The tests don't like that you added the parameters with default values, but the pre-recorded API interactions that we use for the tests don't have those parameters (yet). If you drop the `default`s from the spec, this particular test will succeed.

Overall the tests will still fail tho, as you've added new modules, but did not add any tests for those. I can show you how (the TL;DR is in https://github.com/theforeman/foreman-ansible-modules/blob/develop/docs/testing.md#writing-tests but it's not strictly trivial when doing the first time) or do it for you if you prefer?

That said, would you mind splitting up this PR in three? one for the user module, one for the organization module, and one for the new info modules? That would make merging them easier/faster :)

2023-03-17 10:16 UTC, evgeni commented on plugins/modules/user.py
> +            disabled=dict(required=False, type='bool', default=False),
```suggestion
            disabled=dict(required=False, type='bool'),
```

Please don't set defaults unless really necessary. Ideally we depend on the API to provide those defaults to us.

2023-03-17 10:16 UTC, evgeni commented on plugins/modules/user.py
> +            mail_enabled=dict(required=False, type='bool', default=False),
```suggestion
            mail_enabled=dict(required=False, type='bool'),
```

Please don't set defaults unless really necessary. Ideally we depend on the API to provide those defaults to us.

2023-03-17 17:26 UTC, closed without merging