Added location role
theforeman/foreman-ansible-modules pull request #1623
Opened 2023-06-08 10:01 UTC by alawong

Added a location role which loops through a list of locations foreman_locations and creates them on Satellite server using the foreman location module.

2023-06-23 09:59 UTC, evgeni requested changes
Thanks Alan! And sorry it took so long to get this reviewed!

Overall, this looks good. I posted two comments inline, but nothing major.

One thing that is missing right now are tests. Given our test suite is a bit involved, I can understand if you say that you'd prefer not to touch even more things right now (and would offer you to just do the tests for you), or, if you want of course, you could try to write tests and I'll help you getting there? Absolutely up to you.

2023-06-23 09:59 UTC, evgeni commented on roles/locations/tasks/main.yml
> +    parameters: "{{ item.parameters | default(omit) }}"
```suggestion
    parameters: "{{ item.parameters | default(omit) }}"
    ignore_types: "{{ item.ignore_types | default(omit) }}"
```

you forgot this one parameter :)

2023-06-23 09:59 UTC, evgeni commented on roles/locations/README.md
> +This role creates and manages Satellite locations.
```suggestion
This role creates and manages Foreman locations.
```

(the branding happens automatically, here we keep the Foreman name)

2023-06-23 10:47 UTC, alawong commented
I have made the requested changes, and added the test playbook named locations_role.yml. Please review!

2023-06-26 09:45 UTC, evgeni approved these changes

2023-06-26 09:45 UTC, merged