Add proxy options to template sync playbook
theforeman/foreman-ansible-modules pull request #1795
Opened 2024-11-11 21:56 UTC by adamlazik1

relates to https://github.com/theforeman/foreman_templates/pull/191.

2024-11-12 08:06 UTC, evgeni requested changes
You don't have to pass IDs around, our abstraction layer can resolve entities for you :)

I've proposed changes (untested) that should do exactly that, treat "http_proxy" as an entity, and look it up via the API if passed.

2024-11-12 08:06 UTC, evgeni commented on plugins/modules/templates_import.py
> +    type: int
```suggestion
  http_proxy:
    description:
      - HTTP proxy to use for template sync.
      - Use this parameter together with C(http_proxy_policy=selected)
    required: false
    type: str
```

2024-11-12 08:06 UTC, evgeni commented on plugins/modules/templates_import.py
> +            http_proxy_id=dict(type='int'),
```suggestion
            http_proxy=dict(type='entity'),
```

2024-11-12 08:06 UTC, evgeni commented on tests/test_playbooks/tasks/templates_import.yml
> +    http_proxy_id: "{{ templates_import_http_proxy_id | default(omit) }}"
```suggestion
    http_proxy: "{{ templates_import_http_proxy | default(omit) }}"
```

2024-11-12 10:24 UTC, evgeni commented
the diff looks good to me!
thanks!

2024-11-12 11:07 UTC, adamlazik1 commented
Hey @evgeni , I tried the patch but it does not seem to work:
```
ansible-playbook -i ,localhost -c local -e foreman_username=admin -e foreman_password=changeme -e templates_import_http_proxy='https proxy' -e templates_import_http_proxy_policy=selected -e foreman_server_url=http://foreman-dev.example.com -e foreman_validate_certs=false test.yaml  --module-path='foreman-ansible-modules/plugins/modules'

PLAY [all] ***********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Sync templates in from a git repo] *****************************************************************************************************************************************************************************************************
[WARNING]: You have configured a plain HTTP server URL. All communication will happen unencrypted.
fatal: [localhost]: FAILED! => {"changed": false, "error": {"message": "Couldn't find HttpProxy without an ID"}, "msg": "Error while performing import on templates: 422 Client Error: Unprocessable Content for url: http://foreman-dev.example.com/api/templates/import"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
The http proxy id param did not get passed to the API. Any idea what could be the issue?

2024-11-12 11:21 UTC, adamlazik1 commented
> Hey @evgeni , I tried the patch but it does not seem to work:
> 
> ```
> ansible-playbook -i ,localhost -c local -e foreman_username=admin -e foreman_password=changeme -e templates_import_http_proxy='https proxy' -e templates_import_http_proxy_policy=selected -e foreman_server_url=http://foreman-dev.example.com -e foreman_validate_certs=false test.yaml  --module-path='foreman-ansible-modules/plugins/modules'
> 
> PLAY [all] ***********************************************************************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Sync templates in from a git repo] *****************************************************************************************************************************************************************************************************
> [WARNING]: You have configured a plain HTTP server URL. All communication will happen unencrypted.
> fatal: [localhost]: FAILED! => {"changed": false, "error": {"message": "Couldn't find HttpProxy without an ID"}, "msg": "Error while performing import on templates: 422 Client Error: Unprocessable Content for url: http://foreman-dev.example.com/api/templates/import"}
> 
> PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
> localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
> ```
> 
> The http proxy id param did not get passed to the API. Any idea what could be the issue?

:facepalm: nevermind I forgot to update my test file. Yeah it works as intended so I now just wait for linked PR to get merged before I mark this ready for merge.

```
ansible-playbook -i ,localhost -c local -e foreman_username=admin -e foreman_password=changeme -e 'templates_import_http_proxy="https proxy"' -e templates_import_http_proxy_policy=selected -e foreman_server_url=http://foreman-dev.example.com -e foreman_validate_certs=false test.yaml  --module-path='foreman-ansible-modules/plugins/modules'

PLAY [all] ***********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Sync templates in from a git repo] *****************************************************************************************************************************************************************************************************
[WARNING]: You have configured a plain HTTP server URL. All communication will happen unencrypted.
changed: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

2024-11-12 11:21 UTC, evgeni commented on plugins/modules/templates_import.py
>          required_plugins=[('templates', ['*'])],
You can add
```suggestion
        required_plugins=[('templates', ['*'])],
        required_if=[('http_proxy_policy', 'selected', ('http_proxy'))],
```
to enforce the requirement at ansible level too

2024-11-12 11:22 UTC, evgeni commented
> 🤦 nevermind I forgot to update my test file. Yeah it works as intended so now I just wait for linked PR to get merged before I mark this ready for merge.

Phew. Your PR to templates looks correct, and the same lookup works in many other places, so it would be very weird if it wouldn't work here.

2024-11-12 11:34 UTC, evgeni commented on plugins/modules/templates_import.py
> +        required_if=[('http_proxy_policy', 'selected', ('http_proxy'))],
```suggestion
        required_if=[('http_proxy_policy', 'selected', ['http_proxy'])],
```

I'm stupid, sorry.

2024-11-12 11:57 UTC, adamlazik1 commented on plugins/modules/templates_import.py
> +        required_if=[('http_proxy_policy', 'selected', ('http_proxy'))],
No problem, I just figured it out myself too :smile:

2024-11-13 09:27 UTC, evgeni approved these changes

2024-11-29 13:15 UTC, adamlazik1 commented
This is now ready to be merged.

2024-11-29 13:22 UTC, evgeni reviewed
minor doc fix, I'll apply this myself

2024-11-29 13:22 UTC, evgeni commented on plugins/modules/templates_import.py
> +      - If you choose 'selected', provide the http_proxy_id parameter.
```suggestion
      - If you choose 'selected', provide the C(http_proxy) parameter.
```

2024-11-29 13:22 UTC, evgeni commented on plugins/modules/templates_import.py
> +      - You can choose no HTTP proxy, global HTTP proxy, or a custom HTTP proxy ('selected')
```suggestion
      - You can choose no HTTP proxy, global HTTP proxy, or a custom HTTP proxy (C(selected))
```

2024-11-29 13:26 UTC, evgeni commented
Whatever the codecov comment does here.

2024-11-29 13:31 UTC, merged