sync inventory credential doc strings with the rest
theforeman/foreman-ansible-modules pull request #950
Opened 2020-09-11 12:02 UTC by evgeni

also drop the localhost:3000 default, that'll never work

2020-09-11 12:06 UTC, mdellweg requested changes
I'm ok with making that change, but it is a breaking change , so it needs a changelog.

2020-09-11 12:11 UTC, evgeni commented
the default drop is breaking? yeah, somehow that's right. but that'd mean a 2.x which I'd like to avoid for now.

2020-09-15 14:56 UTC, pondrejk approved these changes

2020-09-16 08:13 UTC, mdellweg approved these changes

2020-09-16 08:13 UTC, merged